require "rubygems"
require "json"
require "rest_client"
require "rhogallery-api/version"
require "rhogallery-api/rho_gallery"
require "rhogallery-api/base"
require "rhogallery-api/consumer"
require "rhogallery-api/group"

#ENV['rhogallery_api_url'] = "https://appstaging.rhohub.com/rhogallery/api/v1/:username/:resource.json"
ENV['rhogallery_api_url'] = "http://rhohub.local/rhogallery/api/v1/:username/:resource.json"